// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: celestia/core/v1/tx/tx.proto

package tx

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TxStatusRequest is the request type for the TxStatus gRPC method.
type TxStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// this is the hex encoded transaction hash (should be 64 characters long representing 32 bytes)
	TxId          string `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxStatusRequest) Reset() {
	*x = TxStatusRequest{}
	mi := &file_celestia_core_v1_tx_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxStatusRequest) ProtoMessage() {}

func (x *TxStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_celestia_core_v1_tx_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxStatusRequest.ProtoReflect.Descriptor instead.
func (*TxStatusRequest) Descriptor() ([]byte, []int) {
	return file_celestia_core_v1_tx_tx_proto_rawDescGZIP(), []int{0}
}

func (x *TxStatusRequest) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

// TxStatusResponse is the response type for the TxStatus gRPC method.
type TxStatusResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Height int64                  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Index  uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	// execution_code is returned when the transaction has been committed
	// and returns whether it was successful or errored. A non zero
	// execution code indicated an error.
	ExecutionCode uint32 `protobuf:"varint,3,opt,name=execution_code,json=executionCode,proto3" json:"execution_code,omitempty"`
	// error log for failed transactions.
	Error string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	// status is the status of the transaction.
	Status        string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxStatusResponse) Reset() {
	*x = TxStatusResponse{}
	mi := &file_celestia_core_v1_tx_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxStatusResponse) ProtoMessage() {}

func (x *TxStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_celestia_core_v1_tx_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxStatusResponse.ProtoReflect.Descriptor instead.
func (*TxStatusResponse) Descriptor() ([]byte, []int) {
	return file_celestia_core_v1_tx_tx_proto_rawDescGZIP(), []int{1}
}

func (x *TxStatusResponse) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *TxStatusResponse) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *TxStatusResponse) GetExecutionCode() uint32 {
	if x != nil {
		return x.ExecutionCode
	}
	return 0
}

func (x *TxStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TxStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_celestia_core_v1_tx_tx_proto protoreflect.FileDescriptor

const file_celestia_core_v1_tx_tx_proto_rawDesc = "" +
	"\n" +
	"\x1ccelestia/core/v1/tx/tx.proto\x12\x13celestia.core.v1.tx\x1a\x1cgoogle/api/annotations.proto\"&\n" +
	"\x0fTxStatusRequest\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\"\x95\x01\n" +
	"\x10TxStatusResponse\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x03R\x06height\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\x12%\n" +
	"\x0eexecution_code\x18\x03 \x01(\rR\rexecutionCode\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status2\x83\x01\n" +
	"\x02Tx\x12}\n" +
	"\bTxStatus\x12$.celestia.core.v1.tx.TxStatusRequest\x1a%.celestia.core.v1.tx.TxStatusResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/celestia/core/v1/tx/{tx_id}B1Z/github.com/celestiaorg/celestia-app/app/grpc/txb\x06proto3"

var (
	file_celestia_core_v1_tx_tx_proto_rawDescOnce sync.Once
	file_celestia_core_v1_tx_tx_proto_rawDescData []byte
)

func file_celestia_core_v1_tx_tx_proto_rawDescGZIP() []byte {
	file_celestia_core_v1_tx_tx_proto_rawDescOnce.Do(func() {
		file_celestia_core_v1_tx_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_celestia_core_v1_tx_tx_proto_rawDesc), len(file_celestia_core_v1_tx_tx_proto_rawDesc)))
	})
	return file_celestia_core_v1_tx_tx_proto_rawDescData
}

var file_celestia_core_v1_tx_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_celestia_core_v1_tx_tx_proto_goTypes = []any{
	(*TxStatusRequest)(nil),  // 0: celestia.core.v1.tx.TxStatusRequest
	(*TxStatusResponse)(nil), // 1: celestia.core.v1.tx.TxStatusResponse
}
var file_celestia_core_v1_tx_tx_proto_depIdxs = []int32{
	0, // 0: celestia.core.v1.tx.Tx.TxStatus:input_type -> celestia.core.v1.tx.TxStatusRequest
	1, // 1: celestia.core.v1.tx.Tx.TxStatus:output_type -> celestia.core.v1.tx.TxStatusResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_celestia_core_v1_tx_tx_proto_init() }
func file_celestia_core_v1_tx_tx_proto_init() {
	if File_celestia_core_v1_tx_tx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_celestia_core_v1_tx_tx_proto_rawDesc), len(file_celestia_core_v1_tx_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_celestia_core_v1_tx_tx_proto_goTypes,
		DependencyIndexes: file_celestia_core_v1_tx_tx_proto_depIdxs,
		MessageInfos:      file_celestia_core_v1_tx_tx_proto_msgTypes,
	}.Build()
	File_celestia_core_v1_tx_tx_proto = out.File
	file_celestia_core_v1_tx_tx_proto_goTypes = nil
	file_celestia_core_v1_tx_tx_proto_depIdxs = nil
}
